### ISSUE TITLE
GetAuthContext -> Authenticate -> uO and uB callbacks

### ISSUE THREAD

**Issue by ryanhburbank** [carterjones/signalr#11]
Hi,

I'm attempting to implement against the Bittrex API using your library, was wondering how I can register callbacks for the __u0__ & __uB__ events.  Having gone through your code and your examples I didn't see a clear way to register.

link to relevant text in docs [here](https://github.com/Bittrex/bittrex.github.io#authenticate)

Or do I simply need to handle them through a single msgHandler?

**Comment by carterjones** [comment]
Hi @ryanhburbank, I'm not familiar with the details of the Bittrex API. However, the basic idea is that you would define your own the msgHandler function which would then handle whatever events you are interested in. Beyond that, I'm afraid I can't offer any support for anything specific to Bittrex. If there is a problem with the signalr code, I'd be happy to assist in fixing it :)

**Comment by ryanhburbank** [comment]
Hi Carter, sounds good, I'll continue working on it on my end then, thanks!
