### ISSUE TITLE
How I can use proxy?

### ISSUE THREAD

**Issue by math-88** [carterjones/signalr#13]
c := signalr.New(
		"site.com",
		"1.5",
		"/signalr",
		`[{"name":"c"}]`,
		nil,
	)

roundtripper := &http.Transport{
			Proxy: http.ProxyURL(proxyURL),
		}
c.HTTPClient.Transport = roundtripper
c.Headers["Proxy-Authorization"] = proxyBasicAuthString

// TLS settings ho having effects
tlsConfig := &tls.Config{
    ServerName:         "site.com",
    InsecureSkipVerify: true,
    // MinVersion:         tls.VersionTLS12,
    // MaxVersion:         tls.VersionTLS12,
  }
c.TLSClientConfig = tlsConfig

========================================
ERROR. connect failed: xconnect failed: 403 Forbidden, retry 0: websocket: bad handshake

wss://site.com/signalr/connect?clientProtocol=1.5&connectionData=%5B....
This request in library does not go through a proxy.

**Comment by carterjones** [comment]
Thanks for the report @math-88. I just added support for proxies.

You can see some examples here:
* https://github.com/carterjones/signalr/tree/master/examples/proxy-simple
* https://github.com/carterjones/signalr/tree/master/examples/proxy-authenticated

Hopefully this provides a solution for you. I'll close the comment for now, but if the proxy still doesn't work for you, please let me know so I can improve this library. Thanks!
