### ISSUE TITLE
Add Custom Parameters on Connect

### ISSUE THREAD

**Issue by tacoo** [carterjones/signalr#5]
Hi, Thank you for the great liberally! I really like it.

One thing I noticed that my project needs to add custom parameters when calling endpoints.
Is there way to add custom parameters other than `connectionData`?

It would be great if I can do something like this.
```
host := "example.com"
protocol := "2.0"
endpoint := "/signalr"
params := map[string]string{
	"connectionData" : "abc"
	"x_key" : "x_val"
}

// Prepare a SignalR client.
c := signalr.New(host, protocol, endpoint, params)

```

Thank you,

**Comment by carterjones** [comment]
Thanks for submitting the issue! I really like this idea.

Do the parameters remain the same for every call? For instance, assuming all the normal parameters are also being passed in, would the calls look like this?

1. example.com/signalr/negotiate?x_key=x_val
2. example.com/signalr/connect?x_key=x_val
3. example.com/signalr/start?x_key=x_val

or could they look like this?

1. example.com/signalr/negotiate?x_key=x_val
2. example.com/signalr/connect?y_key=y_val
3. example.com/signalr/start?z_key=z_val

or perhaps this?

1. example.com/signalr/negotiate?x_key=x_val
2. example.com/signalr/connect
3. example.com/signalr/start

or maybe something else?

**Comment by tacoo** [comment]
Thank you for your reply.
Looks like they're sending params for every call.

https://github.com/SignalR/SignalR/blob/dev/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.common.js#L282

**Comment by carterjones** [comment]
If you pull down the latest version of the master branch, this should work:

```golang
host := "example.com"
protocol := "2.0"
endpoint := "/signalr"
connectionData := `{"custom":"data"}`
params := map[string]string{"custom-key": "custom-value"}

// Prepare a SignalR client.
c := signalr.New(host, protocol, endpoint, connectionData, params)
```

**Comment by tacoo** [comment]
Thank you :) I will check it soon

**Comment by tacoo** [comment]
I confirmed it! Thank you 👍
