### ISSUE TITLE
Support groupsToken and messageId

### ISSUE THREAD

**Issue by tacoo** [carterjones/signalr#6]
It would be great if we can support `groupsToken` and `messageId` :)

From what I know is, they are capturing `groupsToken` and `messageId` and when trying to `reconnect`, they added it into query params.

https://github.com/SignalR/SignalR/blob/1fba14fa3437e24c204dfaf8a18db3fce8acad3c/src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.common.js#L531

**Comment by tacoo** [comment]
here is my sample

https://github.com/tacoo/signalr/commit/2582521feb94b56fa39cd3dce6aab47a37c77e9e

**Comment by carterjones** [comment]
Thank you for opening this issue and for providing sample code 👍 

I implemented groups token functionality in 16214676c10b293d0017415372bb46aac246cc1a.

When I get a chance, I'll add support for the message ID.

**Comment by tacoo** [comment]
Thank you very much. I will run master branch once message ID supported 👍

**Comment by carterjones** [comment]
The latest version of master now supports tracking the message ID. Hopefully, it works for you :) If not, please let me know any errors or strange behavior you see. Thanks!

**Comment by tacoo** [comment]
Hi, I fetched the latest version of master branch and ran it. But the data feed from signalr suddenly stopped so I quickly check the code then I noticed that `GroupsToken` and `MessageID` are set only when its `Start`. However, these parameters are constantly updated via every message. So that code should be somewhere around `readMessage`.

**Comment by carterjones** [comment]
Thanks for the information. It looks like I had a bug, where I would set the message ID even if the server did not send any data. This means even if was sent once, and then not sent in a later message, the message ID would be erased. Hopefully this diff fixes that: c879f9865f2f758b9af1df3694c06a597fff061e (part of the master branch)

It also adds support for updating the groups token.

**Comment by tacoo** [comment]
I ran it for a couple of minutes and re-connecting function is working correctly(usually the feed stopped in 1 or 2 minutes due to missing `groupsToken` and `messageId`)

The SignalR service I am using is a private(required account) and domestic(required Japanese ID) service so it's hard to test.

Anyway, I like your library and learned golang a lot from your code 👍  Thank you again :)
